const productos = [
  {
    id: 1,
    categoria: "Burgers",
    nombre: "Carne",
    precio: 670,
    img: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-burger-king-argentina//home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Chimiburga_Carne.png",
  },
  {
    id: 2,
    categoria: "Burgers",
    nombre: "Carne Premium",
    precio: 840,
    img: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-burger-king-argentina//home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/BondiolitaKing-morron.png",
  },
  {
    id: 3,
    categoria: "Burgers",
    nombre: "Veggie",
    precio: 700,
    img: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-burger-king-argentina//home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Whopper.png",
  },
  {
    id: 4,
    categoria: "Burgers",
    nombre: "Vegan",
    precio: 750,
    img: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-burger-king-argentina//home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/WhopperVegetal_2604.png",
  },
  {
    id: 5,
    categoria: "Burgers",
    nombre: "Pollo",
    precio: 750,
    img: "https://s3-eu-central-1.amazonaws.com/www.burgerking.com.ar.v2/wp-media-folder-burger-king-argentina//home/ubuntu/preview/menu-app/frontend/apps/marketing-website-wordpress-app/web/app/uploads/sites/5/Chimiburga_Pollo.png",
  },
  {
    id: 10,
    categoria: "Panes",
    nombre: "Pan convencional",
    precio: 0,
    img: "https://i.blogs.es/9b5cc5/pan-facil-y-rapido-1/840_560.jpg",
  },
  {
    id: 11,
    categoria: "Panes",
    nombre: "Pan de campo",
    precio: 0,
    img: "https://i.blogs.es/9b5cc5/pan-facil-y-rapido-1/840_560.jpg",
  },
  {
    id: 12,
    categoria: "Panes",
    nombre: "Pan de salvado",
    precio: 0,
    img: "https://i.blogs.es/9b5cc5/pan-facil-y-rapido-1/840_560.jpg",
  },
  {
    id: 13,
    categoria: "Panes",
    nombre: "Pan con semillas",
    precio: 0,
    img: "https://i.blogs.es/9b5cc5/pan-facil-y-rapido-1/840_560.jpg",
  },
  {
    id: 14,
    categoria: "Panes",
    nombre: "Pan tipo de viena",
    precio: 0,
    img: "https://i.blogs.es/9b5cc5/pan-facil-y-rapido-1/840_560.jpg",
  },
  {
    id: 20,
    categoria: "Aderezos",
    nombre: "Mayonesa",
    precio: 0,
    img: "https://i.blogs.es/8a4ab6/mayonesa_rec/450_1000.jpg",
  },
  {
    id: 21,
    categoria: "Aderezos",
    nombre: "Mostaza",
    precio: 0,
    img: "https://i.blogs.es/8a4ab6/mayonesa_rec/450_1000.jpg",
  },
  {
    id: 22,
    categoria: "Aderezos",
    nombre: "BBQ",
    precio: 0,
    img: "https://i.blogs.es/8a4ab6/mayonesa_rec/450_1000.jpg",
  },
  {
    id: 23,
    categoria: "Aderezos",
    nombre: "Chilli",
    precio: 0,
    img: "https://i.blogs.es/8a4ab6/mayonesa_rec/450_1000.jpg",
  },
  {
    id: 24,
    categoria: "Aderezos",
    nombre: "Ketchup",
    precio: 0,
    img: "https://i.blogs.es/8a4ab6/mayonesa_rec/450_1000.jpg",
  },
  {
    id: 30,
    categoria: "Guarniciones",
    nombre: "Papas fritas",
    precio: 200,
    img: "https://comidaschilenas.com/wp-content/uploads/2020/01/Receta-de-papas-fritas-perfectas.jpg",
  },
  {
    id: 31,
    categoria: "Guarniciones",
    nombre: "Papas noisette",
    precio: 250,
    img: "https://comidaschilenas.com/wp-content/uploads/2020/01/Receta-de-papas-fritas-perfectas.jpg",
  },
  {
    id: 32,
    categoria: "Guarniciones",
    nombre: "Rabas",
    precio: 450,
    img: "https://comidaschilenas.com/wp-content/uploads/2020/01/Receta-de-papas-fritas-perfectas.jpg",
  },
  {
    id: 33,
    categoria: "Guarniciones",
    nombre: "Bastones de mozarella",
    precio: 300,
    img: "https://comidaschilenas.com/wp-content/uploads/2020/01/Receta-de-papas-fritas-perfectas.jpg",
  },
  {
    id: 34,
    categoria: "Guarniciones",
    nombre: "Papas rejilla",
    precio: 200,
    img: "https://comidaschilenas.com/wp-content/uploads/2020/01/Receta-de-papas-fritas-perfectas.jpg",
  },
];
